name: CI (Windows-first)

on:
  push:
    branches: [ main, master, dev, "*" ]
  pull_request:

jobs:
  windows:
    runs-on: windows-latest
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: python/requirements-dev.txt

      - name: Install build deps
        run: |
          python -m pip install -U pip wheel
          pip install -r python/requirements-dev.txt

      - name: Pin NumPy for Python 3.10
        if: matrix.python-version == '3.10'
        run: pip install "numpy<2.3"

      - name: Build & install (editable)
        run: pip install -e .

      - name: Run tests
        run: pytest -q
