name: CI (Windows-first)

on:
  push:
    branches: [ main, master, dev, "*" ]
  pull_request:

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build deps
        run: |
          python -m pip install -U pip
          pip install -r python/requirements-dev.txt
      - name: Build & install (editable)
        run: |
          pip install -e .
      - name: Run tests
        run: |
          pytest -q
